spring:
  application:
    name: cafe-management-app
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:6033/iwo_cafe}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:123456}
  liquibase:
    change-log: classpath:changelog/changelog-master.yaml
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:02faf21f0ac077}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true